### ISSUE TITLE
Accumulator functions

### ISSUE THREAD

**Issue by lkwagner** [WagnerGroup/pyqmc#175]
It'd be nice to have a couple accumulator functions that give information about the data that will be produced. For example:

* keys()
* shapes -> return a dictionary of shapes that will be returned
* information -> any information that should be stored but does not depend on the wave function or electronic positions. For example, ijkl for tbdm.

**Comment by willwheelera** [comment]
It seems like most of the "information" would already be accessible by attributes of the class, e.g. tbdm_acc._ijkl. The advantage that I can see of an extra "information" function is that it can include the relevant keys, in case you/your script didn't know the info in tbdm is under "_ijkl". Is that what you had in mind?

**Comment by lkwagner** [comment]
Resolved by #191.
