### ISSUE TITLE
implement futures alternative to dask

### ISSUE THREAD

**Issue by willwheelera** [WagnerGroup/pyqmc#180]
This was Lucas's idea: the functionality we are using from dask is using futures to keep track of distributed jobs. We don't need the whole dask infrastructure just for this; we can implement our own simpler "client" with futures, so that pyqmc can also be used in parallel without dask.

**Comment by lkwagner** [comment]
Actually this is basically done. The only thing is that some of our objects are not perfectly picklable due to some lambda functions. So if that could be cleaned up then it would just work.

**Comment by willwheelera** [comment]
ok great, I can go through and change the lambda functions. By "done", do you mean there's a built-in python object that we can use as the "client" in our current structure? Like `client=ThreadPoolExecutor(max_workers=2)`?

**Comment by lkwagner** [comment]
yeah you can use an executor for the client, at least in principle.

**Comment by lkwagner** [comment]
I think this will not work unless we remove the lambda function definitions from the objects: Some are overused; for example, there is a lot of repeated code in this get_wrapphase business.
`../pyqmc/ewald.py:        self.ee_const = lambda ne: ne * (ne - 1) / 2 * ijconst + ne * squareconst
../pyqmc/ewald.py:        self.ei_const = lambda ne: -ne * i_sum * ijconst
../pyqmc/ewald.py:        self.e_single = lambda ne: (ne - 1) * ijconst - i_sum * ijconst + squareconst
../pyqmc/ewald.py:        rs = lambda ne: (3 / (4 * np.pi) / (ne * cellvolume)) ** (1 / 3)
../pyqmc/ewald.py:        xc_correction = lambda ne: cexc / rs(ne)
../pyqmc/jastrowspin.py:        a_value = list(map(lambda x: x.value(rvec, r), self.a_basis))
../pyqmc/jastrowspin.py:        b_value = list(map(lambda x: x.value(rvec, r), self.b_basis[1:]))
../pyqmc/multislater.py:        self.get_phase = (lambda x: x / np.abs(x)) if self.iscomplex else np.sign
../pyqmc/multislaterpbc.py:            self.get_phase = lambda x: x / np.abs(x)
../pyqmc/multislaterpbc.py:            self.get_wrapphase = lambda x: np.exp(1j * x)
../pyqmc/multislaterpbc.py:            self.get_wrapphase = lambda x: (-1) ** np.round(x / np.pi)
../pyqmc/obdm.py:                self.get_wrapphase = lambda x: np.exp(1j * x)
../pyqmc/obdm.py:                self.get_wrapphase = lambda x: (-1) ** np.round(x / np.pi)
../pyqmc/slater.py:            self.get_phase = lambda x: x / np.abs(x)
../pyqmc/slater.py:            self.get_wrapphase = lambda x: np.exp(1j * x)
../pyqmc/slater.py:            self.get_wrapphase = lambda x: (-1) ** np.round(x / np.pi)
`

**Comment by willwheelera** [comment]
yup i've already started a branch to work on cleaning those out. I was having an issue with the ewald test, I'll submit a PR when I get it worked out

**Comment by lkwagner** [comment]
It looks like the pull request #190 fixed this issue. Marking resolved.
