### ISSUE TITLE
GPU using cupy

### ISSUE THREAD

**Issue by lkwagner** [WagnerGroup/pyqmc#215]
Matt Turk suggested we look into using cupy for GPU acceleration. 

One way to test this would be to implement the Slater or Jastrow computation. Arrays get allocated on the GPU in evaluate() and then the input/output are the electron positions/wave function values and derivatives.

**Comment by matthewturk** [comment]
feel free to at me: @matthewturk !  I am keen on participating in this if helpful.

**Comment by lkwagner** [comment]
There is a working branch by @willwheelera here: https://github.com/willwheelera/pyqmc/tree/cupy/pyqmc

**Comment by lkwagner** [comment]
This was resolved by #273
