### ISSUE TITLE
Preparing for 0.4.0

### ISSUE THREAD

**Issue by lkwagner** [WagnerGroup/pyqmc#282]
We have done a lot since 0.3.0, including GPU's, lots of bug fixes and so on. I can think of 3 things that we should have for 0.4.0:

* T-Moves
* Rearrangement of `__init__.py` and moving code to an api
* Cleanup of GPU code
* CISD wave functions
* Other cleanup (noted in some other issues)

It would be nice to focus on these things to get a clean 0.4.0 out. Anything else we should do?

**Comment by willwheelera** [comment]
I think we should clean up/update the examples for 0.4.0 as well. I have some new examples in progress.

**Comment by lkwagner** [comment]
What examples are you planning?
