### ISSUE TITLE
Saving energy/overlap error bars in optimize_ortho.py

### ISSUE THREAD

**Issue by kkleiner1** [WagnerGroup/pyqmc#312]
I noticed that the optimize_ortho.py function doesn't calculate and save the error bars for the energy and wf overlaps. Those error bars would be useful when plotting excited state optimizations to check convergence. I figure those error bars would be calculated similarly to those in the ground state optimization within linemin.py, which uses these lines.

en = np.real(np.mean(df["pgradtotal"], axis=0))
en_err = np.std(df["pgradtotal"], axis=0) / np.sqrt(df["pgradtotal"].shape[0])

I'm not quite sure how that would work in optimize_ortho.py. I'd be grateful if someone could look into it. Thanks.

**Comment by lkwagner** [comment]
I think this is something we should do. Actually the whole orthogonal_optimization really needs a refactor to bring its behavior more in line with the other functions, and to separate out the sum of wave function sampler.

**Comment by lkwagner** [comment]
This will be replaced with the new optimizer soon!
