### ISSUE TITLE
distance function dist_i is confusing

### ISSUE THREAD

**Issue by willwheelera** [WagnerGroup/pyqmc#406]
The way RawDistance.dist_i is coded up is hard to understand. It is used in multiple ways, only one of which is documented. For example, we use it to compute electron-atom distances, but pass the atom coordinates in as if they were the electrons. The arguments should be given generic names if we want them to be generic, or we should stick to using it with specific inputs if we want them to be specific.

What shapes do the arguments have in the different use cases? Why is `vec` transposed if it has three dimensions? 

If we have sufficiently different use cases, maybe we should define different functions. Otherwise, we should try to avoid the if statements if possible.

Side note: Every version of MinimalImageDistance.dist_i copies the same code used in RawDistance.dist_i. Maybe we can just call super.dist_i for this.

**Comment by lkwagner** [comment]
Resolved by #413
