### ISSUE TITLE
a problem with 3-body Jastrow factor

### ISSUE THREAD

**Issue by wangf44** [WagnerGroup/pyqmc#432]
I have problem running pyQMC 0.6.1 with three-body Jastrow factor. This problem does not exist in pyQMC 0.6.0.  I am not sure whether the input file is incorrect. Could anyone please check this? Thanks a lot!

The error message and the input file is as the follows:

The error message is:

  File "/home/wangf/pyqmc.calc/new/sd3j/serial/sd3j.py", line 35, in <module>
    pyq.line_minimization(wf, configs, acc, max_iterations=4, verbose=True,
  File "/home/wangf/pyqmc/pyqmc/linemin.py", line 182, in line_minimization
    df_vmc, coords = pyqmc.mc.vmc(
  File "/home/wangf/pyqmc/pyqmc/mc.py", line 249, in vmc
    block_avg, configs = vmc_worker(
  File "/home/wangf/pyqmc/pyqmc/mc.py", line 142, in vmc_worker
    dat = accumulator.avg(configs, wf)
  File "/home/wangf/pyqmc/pyqmc/stochastic_reconfiguration.py", line 83, in avg
    den = self.enacc(configs, wf)
  File "/home/wangf/pyqmc/pyqmc/accumulators.py", line 46, in __call__
    ecp_val = eval_ecp.ecp(self.mol, configs, wf, self.threshold, self.naip)
  File "/home/wangf/pyqmc/pyqmc/eval_ecp.py", line 30, in ecp
    ecp_tot += ecp_ea(mol, configs, wf, e, atom, threshold, naip)[
  File "/home/wangf/pyqmc/pyqmc/eval_ecp.py", line 110, in ecp_ea
    ratio = wf.testvalue(e, epos, mask)[0]
  File "/home/wangf/pyqmc/pyqmc/multiplywf.py", line 108, in testvalue
    zip(*[wf.testvalue(e, epos, mask=mask) for wf in self.wf_factors])
  File "/home/wangf/pyqmc/pyqmc/multiplywf.py", line 108, in <listcomp>
    zip(*[wf.testvalue(e, epos, mask=mask) for wf in self.wf_factors])
  File "/home/wangf/pyqmc/pyqmc/three_body_jastrow.py", line 299, in testvalue
    e_partial_new, a_e = self.single_e_partial(
  File "/home/wangf/pyqmc/pyqmc/three_body_jastrow.py", line 191, in single_e_partial
    di_e = configs.dist.pairwise(self._mol.atom_coords(), epos)
  File "/home/wangf/pyqmc/pyqmc/distance.py", line 68, in pairwise
    assert m1 == m2 or m1 == 1 or m2 == 1, f"can't broadcast first axis {m1} and {m2}"
AssertionError: can't broadcast first axis 2 and 26

The input file is:

if __name__ == "__main__":
    from pyscf import gto, scf, mcscf
    import h5py
    import pyqmc.api as pyq
    import pyqmc.wftools as wftools
    import pyqmc.pyscftools as pyscftools

    mol = gto.Mole()
    mol.build(
        atom = 'N  0  0  0; N  0  0  1.5',
        basis="ccecp-ccpvtz",
        ecp="ccecp",
        symmetry = True,
        verbose = 5,
        output = 'out.n2'
    )
    mydft = scf.RKS(mol)
    mydft.xc = 'b3lyp'
    mydft.chkfile = 'dft.chk'
    mydft.kernel()
    mydft.analyze()

    mol, mf = pyscftools.recover_pyscf("dft.chk", cancel_outputs=False)

    wf, to_opt = pyq.generate_wf(mol, mf, jastrow=[wftools.generate_jastrow,wftools.generate_jastrow3],
                                 jastrow_kws=[{},{}])

    nconfig = 200
    nodal_cutoff=1e-3

    configs = pyq.initial_guess(mol, nconfig)

    acc = pyq.gradient_generator(mol, wf, to_opt, nodal_cutoff=nodal_cutoff)

    pyq.line_minimization(wf, configs, acc, max_iterations=4, verbose=True,
                          hdf_file='opt3j.chk')

**Comment by willwheelera** [comment]
Hi, thanks for bringing this to our attention! This is a bug in our code, ThreeBodyJastrow didn't get updated in a recent change. We have a fix for the problem and it should be up soon.

Your input file looks ok to me!

**Comment by lkwagner** [comment]
I confirmed that your input file works with the latest commit by @willwheelera . If you pull (you may have to force pip to update as the version number has not changed), then it should work.  This is a result of a refactor we did a month or two ago.

Thanks for trying out the development version and helping us find errors!

**Comment by wangf44** [comment]
Thanks a lot! It works now.
