### ISSUE TITLE
Question Regarding T-Moves Implementation in PyQMC

### ISSUE THREAD

**Issue by eric-yu-zhu** [WagnerGroup/pyqmc#439]
# Inquiry Regarding T-Moves Implementation in PyQMC

Dear PyQMC Team,

Firstly, I'd like to express my gratitude for developing and sharing **PyQMC**. It has proven to be an invaluable resource for newcomers like myself learning about QMC methods. However, I have encountered some potential issues with the implementation of T-moves in the code.

For clarity, here is the relevant code snippet from `[dmc.py > def propose_tmoves > line 100]`:

```python
[100] backward_amplitudes = t_amplitudes.copy()
[101] for walker, move in enumerate(selected_moves):
[102]     if move_selected[walker]:
[103]         newpos[walker, :] = moves["configs"].configs[walker, move, :]
[104]         reverse_ratio[walker] = 1.0 / moves["ratio"][walker, move]
[105]         backward_amplitudes[walker, :] *= reverse_ratio[walker]
[106]         # This is the move back to the original position
[107]         backward_amplitudes[walker, move] = (
[108]             reverse_ratio[walker] * moves["weight"][walker, move]
[109]         )
[110]     else:
[111]         newpos[walker, :] = configs.configs[walker, e, :]
[112]         reverse_ratio[walker] = 0.0
```
I would assume that this piece implements Eq. (38) from "Nonlocal pseudopotentials and time-step errors in Diffusion Monte Carlo" [J. Chem. Phys. 154, 214110 (2021)]. I found the implementation may not be consistent with the theory. My reasoning is as follows:

1. After executing line [105], the backward amplitudes are:
```python
backward_amplitudes[walker,:] = t_amplitudes[walker,:] * inv(psi[walker,move] / psi[walker,e])
                              = (ratio[walker,:] * weight[walker,:]) * inv(psi[walker,move] / psi[walker,e])
                              = (psi[walker,:]/psi[walker,e] * weight[walker,:]) * inv(psi[walker,move] / psi[walker,e]) 
                              = psi[walker,:] / psi[walker,move] * weight[walker,:]
```
This line is OK.

2. After executing line [107], the backward amplitude of the selected t-move is:
```python
backward_amplitudes[walker,move] = inv(psi[walker,move] / psi[walker,e]) * weight[walker,move]
                                 = psi[walker,e] / psi[walker,move] * weight[walker,move]
```
This line appears to be questionable. In my opinion, the right one should be:
```python
backward_amplitudes[walker,move] = psi[walker,move] / psi[walker,move] * weight[walker,move]
                                 = weight[walker,move]
```

3. The reuse of wave function ratio is a smart strategy to save computational cost. However, the reuse of weight is not well justified because the weight has a Theta dependence (see Eq. (31)). Note that Theta is the angle between r_i and r_k in the forward amplitude whereas Theta is the angle between r_j and r_k in the backward amplitude (here i is the electron index, j is the selected t-move index, k is the quadrature index). Therefore, the forward weight cannot be reused in the backward calculation.

Could you please confirm whether my interpretation aligns with your implementation intentions? Any clarification would be immensely helpful.

Best,
Eric

**Comment by lkwagner** [comment]
Hi Eric,

Thanks for the comment and thoughts. I don't completely follow your logic there to be honest, but it's been a while since I've looked at the implementation and there are a lot of little details! I have a recollection that the wave function ratio you object to really just "undoes" the ratio that's already in the weights. But I could be misremembering!

A quick way of checking is whether your proposed change would result in smaller timestep errors compared to the current implementation. We know that our current implementation has very similar errors to the one by Umrigar, and has the right tau->0 limit (we checked versus them). Let me know what you get!

Lucas

**Comment by eric-yu-zhu** [comment]
Dear Lucas,

Thank you so much for your quick reply and explanation. I agree that numerical experiments are strong checks of implementation.

On the other hand, the issue reported here is very detailed and subtle. It may escape numerical tests for the following reasons: (a) If l_max of the nonlocal part of pseudopotential is 0 (which is the case of O atom), the weight has no Theta dependence and hence the issue (3) will not show up. However, the issue may still affect higher angular momentum components. (b) The issue reported in (2) affects only one point out of all quadrature points. The error tends to zero in the limit of infinite number of quadrature points. 

If debugging code takes too much time, may I suggest that you check my notes for implementing Eq. (38) of J. Chem. Phys. 154, 214110 (2021). Since the code implements this equation, I can carry out more tests by myself. 

Please see the attached notes. Thank you!

Best,
Eric

[issue_tmove.pdf](https://github.com/WagnerGroup/pyqmc/files/15337922/issue_tmove.pdf)

**Comment by lkwagner** [comment]
Hi Eric,

Well it looks like you have a prediction -- it won't matter for O but it would matter for Ti (for example). Could you do some runs to check that? 

Note that we are already making an approximation because the reverse move is not possible except in the limit of an infinite grid anyway.

Cheers,

Lucas

**Comment by eric-yu-zhu** [comment]
Hi Wagner,

Let me close this discussion for now and keep you posted if anything new found in the future.

Thank you again for deveoping and sharing PyQMC which allows new QMC learners to explore the algorithms.

Best,
Eric
